---
- name: Register vm with the service
  hosts: localhost
  uri:
    url: "https://10.8.99.247/api/services"
    method: POST
    body_format: json
    body:
      action: add_resource
      resources : "billy_vmname10"
    validate_certs: False
    headers:
      X-Auth-Token: "adce6868899428088cae127788786d83"
      Content-Type: "application/json"
    status_code: 200
  register: output

- debug: var=output.json.results[0].success