- hosts: localhost
  vars:
    state_attrs: { 'ip': '2.2.2.2'}

  tasks:
    - name: Set the automate workspace url
      set_fact:
        aws_url: "{{ manageiq.api_url }}/api/{{ manageiq.automate_workspace }}"

    - name: Print connection vars
      debug:
        msg: "URL: {{ manageiq.api_url }} |||||||||||||||||  WORKSPACE:{{ manageiq.automate_workspace }} "


    - name: Fetch the Workspace
      uri:
        url: "{{ aws_url }}"
        method: GET
        validate_certs: False
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
          Content-Type: "application/json"
        status_code: 200
      register: workspace

    - debug: var=workspace

    - name: Set the Extra State Vars
      uri:
        url: "{{ aws_url }}"
        method: POST
        body:
          action: edit
          resource: "{ 'objects': { }, 'state_vars': {{ state_attrs }}}"
        body_format: json
        validate_certs: False
        headers:
          X-Auth-Token: "{{ manageiq.api_token }}"
          Content-Type: "application/json"
        status_code: 200