---
# This playbook prints a simple debug message
- name: Echo Hello, ystream, version, newvm , memorySize
  hosts: localhost

  tasks:
  - debug: msg="Hello,  {{ ystream }}, {{ version }}, {{ myhost }}, {{ newvm }}, {{ memorySize }}, {{ cfme_userid }}, {{ provider_href_slug }}"