---
# This playbook uses the win_ping module to test connectivity using set_vars
- name: Ping
  hosts: all
  vars:
    # ansible_user: '{{ winrm_user }}'
    # ansible_password: '{{ winrm_password }}'
    ansible_port: '5986'
    ansible_connection: 'winrm'
    ansible_winrm_transport: 'ssl'
    ansible_winrm_server_cert_validation: 'ignore'

  tasks:
  - name: ping
    win_ping: