---
- name: Set retry interval
  hosts: localhost
  connection: local
  vars:
  - object: root

  gather_facts: False
  roles:
  - syncrou.manageiq-automate
  - syncrou.manageiq-vmdb

  tasks:
    - name: "Get miq_request object reference"
      manageiq_automate:
        workspace: "{{ workspace }}"
        get_attribute:

          object: "root"
          attribute: "miq_request"

      register: miq_request

    - name: Update user message in miq_request
      manageiq_vmdb:
        href: "{{ miq_request }}"
        action: edit
        data: 
          options:
            user_message: "hello from Ansible"
