---
# This playbook prints a simple debug message
- name: Echo Hello, world!
  hosts: all
  vars:
    ansible_port: '5986'
    ansible_connection: 'winrm'
    ansible_winrm_transport: 'ssl'
    ansible_winrm_server_cert_validation: 'ignore'


  tasks:
  - debug: msg="Hello, world!"