---
# This playbook prints a simple debug message
- name: Echo Hello, world!
  hosts: localhost
  vars:
    testArray: "zero\x1Fone\x1Ftwo"

  tasks:
  - debug: msg="Hello, world!"
  - debug: var=test1
  - debug: var=test2
  - debug: var=test3
  - debug: var=test4
  - debug: msg="{{ testArray }}"
  - debug: var=hosts
  - debug: var=miq_data
  - debug: var=vars