---
# This playbook prints a simple debug message
- name: Echo Hello, world!
  hosts: localhost

  tasks:
  - debug: msg="Hello, world!"
  - debug: var=test1
  - debug: var=test2
  - debug: var=hosts
  - debug: var=miq_data
  - debug: var=vars