---
# This playbook prints a simple debug message from service_vars(s) 
- name: Echo Hello, Fred and Wilma
  hosts: localhost

  tasks:
  - name: "playbooksvc1 - testing service_var__var1a vars"
    set_stats:
      data:
        service_var__var1a: "{{ input1a }}"
        service_var__var1b: "{{ input1b }}"

  - debug: msg="Hello, {{ input1a }} and {{ input1b }}"
 