---
# This playbook set_vars_for_winrm sets input vars for building a winrm connection with service_vars 
# - name: Echo Hello, world!
- hosts: localhost
  # connection: winrm
  tasks:
  - name: "Set input vars for next step"
    set_stats:
      data:
        service_var__my_ip: "{{ winrm_host }}"

  - debug: msg="Hello, {{ winrm_host }}."
# - debug: var=vars
