---
- name: Check a State Var exsits
  hosts: localhost
  connection: local
  vars:
  - object: root

  gather_facts: False
  roles:
  - syncrou.manageiq-automate
  - syncrou.manageiq-vmdb

  tasks:
    - name: "Check a State Var exist"
      manageiq_automate:
        workspace: "{{ workspace }}"
        state_var_exists:
          attribute: "task_id"
      register: task_id

    - debug: msg="task_id:{{ task_id }}"



          