---
# This playbook set_vars_for_winrm sets input vars for building a winrm connection with service_vars 
# - name: Echo Hello, world!
- hosts: localhost
  # connection: winrm
  tasks:
  - name: "Set input vars for next step"
    set_stats:
      data:
        service_var__host_ip: '{{ input_host }}'
        host_ip: '{{ input_host }}'

#  - debug: msg="Hello, {{ input_host }}."
# - debug: var=vars
